#!/bin/bash

# mongod - Startup script for mongod

### BEGIN INIT INFO
# Provides:       mongod
# Required-Start: $network
# Required-Stop: $network
# Default-Start:  2 3 5
# Default-Stop:   0 1 6
# Short-Description: Mongod
# Description:    Mongod
### END INIT INFO

# things from mongod.conf get there by mongod reading it

EZPAARSE_MONGO_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"

# NOTE: if you change any OPTIONS here, you get what you pay for:
# this script assumes all options are in the config file.
CONFIGFILE="${EZPAARSE_MONGO_PATH}/etc/mongod.conf"
PIDFILEPATH="${EZPAARSE_MONGO_PATH}/var/run/mongod.pid"

OPTIONS=" -f $CONFIGFILE"
SYSCONFIG="/etc/sysconfig/mongod"

PIDDIR=`dirname "${PIDFILEPATH}"`
mongod=${MONGOD-/usr/bin/mongod}

if [ -f "$SYSCONFIG" ]; then
    . "$SYSCONFIG"
fi


start()
{

  # Make sure the default pidfile directory exists
  if [ ! -d ${PIDDIR} ]; then
    mkdir -p ${PIDDIR}
  fi

  if [ ! -f ${CONFIGFILE} ]; then
    echo "${CONFIGFILE} not found"
    echo "You should run init-config first"
    exit 1; 
  fi
  # Recommended ulimit values for mongod or mongos
  # See http://docs.mongodb.org/manual/reference/ulimit/#recommended-settings
  #
  #ulimit -f unlimited
  #ulimit -t unlimited
  #ulimit -v unlimited
  #ulimit -n 64000
  #ulimit -m unlimited
  #ulimit -u 32000

  echo -n "Starting mongod: "
  $mongod $OPTIONS >/dev/null 2>&1

  RETVAL=$?
  [ $RETVAL -eq 0 ] && touch ${EZPAARSE_MONGO_PATH}/var/lock/subsys/mongod
  return $RETVAL
}

stop()
{
  echo -n "Stopping mongod: "
 
  kill `cat $PIDFILEPATH` 2>&1

  rm -f "${PIDFILEPATH}"
}

restart () {
	stop
	start
}

RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|force-reload|condrestart}"
    exit 1
esac

exit $RETVAL
